### ISSUE TITLE
gletools no longer available.

### ISSUE THREAD

**Issue by stuaxo** [pabennett/glblox#1]
Hi
  Gletools is no longer available, is it worth shipping it here?

S

**Comment by pabennett** [comment]
Hey, thanks for the info

The only component of gletools being used is the shader compiler which is easily replaced with pyglet-shaders (see: https://github.com/pabennett/WaterCaustics). I'll remove the dependency tomorrow!

**Comment by stuaxo** [comment]
Awesome, wish I'd reported this before :)

S++

**Comment by pabennett** [comment]
Hey, the reference to gletools was removed. Thanks for reporting the problem
